### ISSUE TITLE
Tool Broken. Can someone release a save file for AB+?

### ISSUE THREAD

**Issue by iMonZ** [Zamiell/isaac-save-installer#5]
Tried this tool on modern Operating Systems.
But it doesnt work.
Can someone release the save file?

Error:

> preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
> preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
> +------------------------------------+
> |   The Binding of Isaac: Rebirth    |
> |             (and DLCs)             |
> | Fully Unlocked Save File Installer |
> |               v1.0.6               |
> +------------------------------------+
> 
> If you have any problems with this installer, you can get help in the
> Isaac Speedrunning & Racing Discord server:
> https://discord.com/invite/0Sokdog3miAGKovs
> 
> 015c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
> 015c:fixme:thread:get_thread_times not implemented on this platform
> 015c:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
> preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
> 015c:fixme:wbemprox:client_security_SetBlanket 00000002419BFE40, 00000000010B0860, 10, 0, (null), 3, 3, 0000000000000000, 0
> 015c:fixme:wbemprox:client_security_Release 00000002419BFE40
> 0184:fixme:seh:EnumProcessModulesEx (000000000000009C, 000000000266E610, 4, 000000000266E3B8, 3) semi-stub
> 0190:fixme:seh:EnumProcessModulesEx (0000000000000070, 0000000002F6DC40, 4, 0000000002F6D9E8, 3) semi-stub
> 0188:fixme:seh:EnumProcessModulesEx (00000000000000A0, 000000000296EB40, 4, 000000000296E8E8, 3) semi-stub
> 0180:fixme:seh:EnumProcessModulesEx (00000000000000A4, 000000000236E610, 4, 000000000236E3B8, 3) semi-stub
> 017c:fixme:seh:EnumProcessModulesEx (0000000000000098, 000000000206E0E0, 4, 000000000206DE88, 3) semi-stub
> 0198:fixme:seh:EnumProcessModulesEx (00000000000000A8, 000000000356E610, 4, 000000000356E3B8, 3) semi-stub
> 0194:fixme:seh:EnumProcessModulesEx (00000000000000AC, 000000000326EB40, 4, 000000000326E8E8, 3) semi-stub
> 018c:fixme:seh:EnumProcessModulesEx (00000000000000B0, 0000000002C6EB40, 4, 0000000002C6E8E8, 3) semi-stub
> 0190:fixme:seh:EnumProcessModulesEx (00000000000000B4, 0000000002F6DAE0, 4, 0000000002F6D888, 3) semi-stub
> wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
> 0058:fixme:mountmgr:query_property Unsupported property 0x8
> 0058:fixme:mountmgr:query_property Unsupported property 0x8
> 0058:fixme:mountmgr:query_property Unsupported property 0x8
> 015c:fixme:netapi32:NetQueryDisplayInformation Level 1 partially implemented
> 015c:fixme:netapi32:NetUserGetLocalGroups (L"", L"mvg", 0, 00000001, 000000000021F648 -1, 000000000021F628, 000000000021F5C0) stub!
> 015c:fixme:netapi32:NetUserGetLocalGroups (L"", L"Administrator", 0, 00000001, 000000000021F648 -1, 000000000021F628, 000000000021F5C0) stub!
> 015c:fixme:netapi32:NetUserGetLocalGroups (L"", L"Guest", 0, 00000001, 000000000021F648 -1, 000000000021F628, 000000000021F5C0) stub!
> Which game do you want to manage the save files for?
> 1) The Binding of Isaac: Rebirth
> 2) The Binding of Isaac: Afterbirth
> 3) The Binding of Isaac: Afterbirth+ (Vanilla through Booster Pack 4)
> 4) The Binding of Isaac: Afterbirth+ (Booster Pack 5)
> 5) The Binding of Isaac: Repentance
> [Type the number and press enter.]
> 4
> 
> Error: Failed to get the Windows registry key: Software\Valve\Steam
> You can now close this window.

**Comment by iMonZ** [comment]
> Tried this tool on modern Operating Systems. But it doesnt work. Can someone release the save file?
> 
> Error:
> 
> > preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
> > preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
> > +------------------------------------+
> > |   The Binding of Isaac: Rebirth    |
> > |             (and DLCs)             |
> > | Fully Unlocked Save File Installer |
> > |               v1.0.6               |
> > +------------------------------------+
> > If you have any problems with this installer, you can get help in the
> > Isaac Speedrunning & Racing Discord server:
> > https://discord.com/invite/0Sokdog3miAGKovs
> > 015c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
> > 015c:fixme🧵get_thread_times not implemented on this platform
> > 015c:fixme:ole:CoInitializeSecurity 0000000000000000, -1, 0000000000000000, 0000000000000000, 0, 3, 0000000000000000, 0, 0000000000000000 stub
> > preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
> > 015c:fixme:wbemprox:client_security_SetBlanket 00000002419BFE40, 00000000010B0860, 10, 0, (null), 3, 3, 0000000000000000, 0
> > 015c:fixme:wbemprox:client_security_Release 00000002419BFE40
> > 0184:fixme:seh:EnumProcessModulesEx (000000000000009C, 000000000266E610, 4, 000000000266E3B8, 3) semi-stub
> > 0190:fixme:seh:EnumProcessModulesEx (0000000000000070, 0000000002F6DC40, 4, 0000000002F6D9E8, 3) semi-stub
> > 0188:fixme:seh:EnumProcessModulesEx (00000000000000A0, 000000000296EB40, 4, 000000000296E8E8, 3) semi-stub
> > 0180:fixme:seh:EnumProcessModulesEx (00000000000000A4, 000000000236E610, 4, 000000000236E3B8, 3) semi-stub
> > 017c:fixme:seh:EnumProcessModulesEx (0000000000000098, 000000000206E0E0, 4, 000000000206DE88, 3) semi-stub
> > 0198:fixme:seh:EnumProcessModulesEx (00000000000000A8, 000000000356E610, 4, 000000000356E3B8, 3) semi-stub
> > 0194:fixme:seh:EnumProcessModulesEx (00000000000000AC, 000000000326EB40, 4, 000000000326E8E8, 3) semi-stub
> > 018c:fixme:seh:EnumProcessModulesEx (00000000000000B0, 0000000002C6EB40, 4, 0000000002C6E8E8, 3) semi-stub
> > 0190:fixme:seh:EnumProcessModulesEx (00000000000000B4, 0000000002F6DAE0, 4, 0000000002F6D888, 3) semi-stub
> > wine: Read access denied for device L"\??\Z:\", FS volume label and serial are not available.
> > 0058:fixme:mountmgr:query_property Unsupported property 0x8
> > 0058:fixme:mountmgr:query_property Unsupported property 0x8
> > 0058:fixme:mountmgr:query_property Unsupported property 0x8
> > 015c:fixme:netapi32:NetQueryDisplayInformation Level 1 partially implemented
> > 015c:fixme:netapi32:NetUserGetLocalGroups (L"", L"mvg", 0, 00000001, 000000000021F648 -1, 000000000021F628, 000000000021F5C0) stub!
> > 015c:fixme:netapi32:NetUserGetLocalGroups (L"", L"Administrator", 0, 00000001, 000000000021F648 -1, 000000000021F628, 000000000021F5C0) stub!
> > 015c:fixme:netapi32:NetUserGetLocalGroups (L"", L"Guest", 0, 00000001, 000000000021F648 -1, 000000000021F628, 000000000021F5C0) stub!
> > Which game do you want to manage the save files for?
> > 
> > 1. The Binding of Isaac: Rebirth
> > 2. The Binding of Isaac: Afterbirth
> > 3. The Binding of Isaac: Afterbirth+ (Vanilla through Booster Pack 4)
> > 4. The Binding of Isaac: Afterbirth+ (Booster Pack 5)
> > 5. The Binding of Isaac: Repentance
> >    [Type the number and press enter.]
> >    4
> > 
> > Error: Failed to get the Windows registry key: Software\Valve\Steam
> > You can now close this window.

I found the save file but where should I put it to?

**Comment by Zamiell** [comment]
https://github.com/Zamiell/isaac-faq/blob/main/directories-and-save-files.md
